apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-api-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sameedshoaibb/devops-web-api.git
    targetRevision: main
    path: banking-api/helm
    helm:
      valueFiles:
        - values.yaml
        - values.prod.yaml
      parameters:
        - name: app.imageTag
          value: "v1.0.2"
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-api-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sameedshoaibb/devops-web-api.git
    targetRevision: main
    path: banking-api/helm
    helm:
      valueFiles:
        - values.yaml
        - values.staging.yaml
      parameters:
        - name: app.imageTag
          value: "v1.0.2-staging"
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-api-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-api-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sameedshoaibb/devops-web-api.git
    targetRevision: main
    path: banking-api/helm
    helm:
      valueFiles:
        - values.yaml
        - values.dev.yaml
      parameters:
        - name: app.imageTag
          value: "v1.0.2-dev"
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-api-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  revisionHistoryLimit: 10