# NOTE: Secrets are pre-created outside of Helm for security reasons.
# 
# Create the secret with:
# kubectl create secret generic banking-api-key \
#   --from-literal=adminApiKey=YOUR_SECRET_KEY \
#   -n banking-api
