# NOTE: Secrets are pre-created outside of Helm for security reasons.
# 
# Create the secret with:
# kubectl create secret generic care-banking-app-key \
#   --from-literal=adminApiKey=sameed \
#   -n care-banking-app
