# Staging environment overrides

replicaCount: 1

app:
  imageTag: v0.0.17
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"

nginx:
  image: nginx
  imageTag: "1.26.1-alpine"
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "75m"
      memory: "96Mi"
    limits:
      cpu: "150m"
      memory: "192Mi"

cronjob:
  schedule: "0 3 * * *"

resourceQuota:
  hard:
    requests:
      cpu: "3"
      memory: "3Gi"
      storage: "15Gi"
    limits:
      cpu: "6"
      memory: "6Gi"

priorityClass:
  value: 750
