apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config-template
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
data:
  config.json: |
    {
      "port": {{ .Values.app.port }},
      "adminApiKey": "${ADMIN_API_KEY}"
    }

