apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-data-file
  labels:
    app: {{ .Values.app.name }}
data:
  data.txt: |
    Data file content for banking-api
    Created at deployment time
    This file is mounted to /data/dat.txt
