apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: {{ .Values.app.version }}
    spec:
      serviceAccountName: {{ .Values.app.name }}
      priorityClassName: {{ .Values.app.name }}-critical
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: config-init
          image: {{ .Values.initContainer.image }}
          command: ['sh', '-c']
          args:
            - |
              sed "s|\${ADMIN_API_KEY}|${ADMIN_API_KEY}|g" /mnt/config-template/config.json > /config/config.json
              chmod 444 /config/config.json
          env:
            - name: ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: banking-api-key
                  key: adminApiKey
          resources:
            requests:
              cpu: {{ .Values.initContainer.resources.requests.cpu }}
              memory: {{ .Values.initContainer.resources.requests.memory }}
            limits:
              cpu: {{ .Values.initContainer.resources.limits.cpu }}
              memory: {{ .Values.initContainer.resources.limits.memory }}
          volumeMounts:
            - name: config-template
              mountPath: /mnt/config-template
            - name: app-config
              mountPath: /config
            # - name: persistent-data
            #   mountPath: /data  
            # - name: data-file
            #   mountPath: /data/dat.txt
            #   subPath: dat.txt
      containers:
        - name: banking-api
          image: {{ .Values.app.image }}:{{ .Values.app.imageTag }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          ports:
            - name: app-port
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: CONFIG_FILE
              value: /config/config.json
            - name: MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
          livenessProbe:
            httpGet:
              path: {{ .Values.app.livenessProbe.path }}
              port: app-port
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.readinessProbe.path }}
              port: app-port
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
          resources:
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }}
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory }}
          volumeMounts:
            - name: config-template
              mountPath: /mnt/config-template
            - name: app-config
              mountPath: /config
            - name: persistent-data
              mountPath: /data  
            - name: data-file
              mountPath: /data/data.txt
              subPath: data.txt

        - name: nginx-proxy
          image: {{ .Values.nginx.image }}:{{ .Values.nginx.imageTag }}
          imagePullPolicy: {{ .Values.nginx.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.nginx.resources.requests.cpu }}
              memory: {{ .Values.nginx.resources.requests.memory }}
            limits:
              cpu: {{ .Values.nginx.resources.limits.cpu }}
              memory: {{ .Values.nginx.resources.limits.memory }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-logs
              mountPath: /var/log/nginx
            - name: nginx-conf-d
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config-template
          configMap:
            name: {{ .Values.app.name }}-config-template
            defaultMode: 0444
        - name: app-config
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
        - name: persistent-data
          persistentVolumeClaim:
            claimName: banking-api-pvc
        - name: data-file
          configMap:
            name: {{ .Values.app.name }}-data-file
            defaultMode: 0444

        - name: nginx-config
          configMap:
            name: {{ .Values.app.name }}-nginx
        - name: nginx-cache
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.volumes.nginxCache.sizeLimit }}
        - name: nginx-run
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.volumes.nginxRun.sizeLimit }}
        - name: nginx-logs
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.volumes.nginxLogs.sizeLimit }}
        - name: nginx-conf-d
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.volumes.nginxConfD.sizeLimit }}
