apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app.name }}-pv
  labels:
    app: {{ .Values.app.name }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/banking-api-data
    type: DirectoryOrCreate

