apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-pvc
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}

  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
