apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.app.name }}-quota
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.hard.requests.cpu | quote }}
    limits.cpu: {{ .Values.resourceQuota.hard.limits.cpu | quote }}
    requests.memory: {{ .Values.resourceQuota.hard.requests.memory | quote }}
    limits.memory: {{ .Values.resourceQuota.hard.limits.memory | quote }}
    requests.storage: {{ .Values.resourceQuota.hard.storage | quote }}
