# TO add VPA, we need metric servers and other components installed in the cluster. This is a demo config.

# apiVersion: autoscaling.k8s.io/v1
# kind: VerticalPodAutoscaler
# metadata:
#   name: {{ .Values.app.name }}
#   namespace: {{ .Release.Namespace }}
#   labels:
#      app: {{ .Values.app.name }}
# spec:
#   targetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: {{ .Values.app.name }}
#   updatePolicy:
#     updateMode: "Off"
